alter session set "_ORACLE_SCRIPT"=true;

CREATE USER PROJETO1 IDENTIFIED BY PROJETO1;

CREATE SEQUENCE PROJETO1.SEQ_HASH;

CREATE TABLE PROJETO1.TB_COORDENADAS ( 
	ID_COORD             integer   ,
	LATITUDE             char(5)   ,
	LONGITUDE            char(5)   ,
	CONSTRAINT PK_TB_COORDENAD_ID_COORD UNIQUE ( ID_COORD ) 
 );

CREATE TABLE PROJETO1.TB_HASHTAGS ( 
	ID_HASH              integer   ,
	HASHTAG              varchar2(300)   ,
	CONSTRAINT PK_TB_HASHTAGS_ID_HASH UNIQUE ( ID_HASH ) 
 );

CREATE TABLE PROJETO1.TB_LOCALIDADE ( 
	ID_LOCALIDADE        integer  NOT NULL ,
	COD_PAIS             integer   ,
	NOME_PAIS            varchar2(50)   ,
	ID_COORD             integer   ,
	CONSTRAINT PK_TB_LOCALIDAD_ID_TWEET UNIQUE ( ID_LOCALIDADE ) 
 );

CREATE TABLE PROJETO1.TB_RETWEET ( 
	ID_RETWEET           integer  NOT NULL ,
	TEXTO_RETWEET        varchar2(300)   ,
	ID_HASH              integer   ,
	ID_TWEET             integer  NOT NULL ,
	ID_USER_RETWEET      integer  NOT NULL ,
	CONSTRAINT PK_TB_RETWEET_ID_RETWEET UNIQUE ( ID_RETWEET ) 
 );

CREATE TABLE PROJETO1.TB_USER_QUOTED ( 
	ID_USER_QUOTED       integer   ,
	DATA_CADASTRO        timestamp   ,
	NUM_SEGUIDORES       integer   ,
	CONSTRAINT PK_TB_USER_QUOT_ID_USER_QUOT UNIQUE ( ID_USER_QUOTED ) 
 );

CREATE TABLE PROJETO1.TB_USER_RETWEET ( 
	ID_USER_RETWEET      integer   ,
	DATA_CADASTRO        timestamp   ,
	NUM_SEGUIDORES       integer   ,
	CONSTRAINT PK_TB_USER_RETW_ID_USER_RETW UNIQUE ( ID_USER_RETWEET ) 
 );

CREATE TABLE PROJETO1.TB_USER_TWEET ( 
	ID_USER_TWEET        integer  NOT NULL ,
	DATA_CADASTRO        timestamp   ,
	NUM_SEGUIDORES       integer   ,
	CONSTRAINT PK_TB_USER_TWEE_ID_USER_TWEE UNIQUE ( ID_USER_TWEET ) 
 );

CREATE TABLE PROJETO1.TB_TWEET ( 
	ID_TWEET             integer   ,
	DATA_TWEET           timestamp   ,
	IDIOMA_TWEET         varchar2(50)   ,
	TEXTO_TWEET          varchar2(300)   ,
	NUM_RETWEETS         integer   ,
	STATUS_TWEET         char(1)   ,
	ID_USER_TWEET        integer  NOT NULL ,
	ID_HASH              integer   ,
	ID_LOCALIDADE        integer  NOT NULL ,
	CONSTRAINT PK_TB_TWEET_ID_TWEET UNIQUE ( ID_TWEET ) 
 );

CREATE TABLE PROJETO1.TB_USER_MENTIONS ( 
	ID_USER_MENTIONS     integer   ,
	NOME_USER            varchar2(150)   ,
	ID_TWEET             integer   ,
	ID_RETWEET           integer   ,
	CONSTRAINT PK_TB_USER_MENT_ID_USER_MENT UNIQUE ( ID_USER_MENTIONS ) 
 );

CREATE TABLE PROJETO1.TB_EXTENDED_TWEETS ( 
	ID_EXT_TWEET         integer   ,
	TEXTO_COMPLETO       varchar2(250)   ,
	ID_USER_MENTIONS     integer  NOT NULL ,
	CONSTRAINT PK_TB_EXTENDED__ID_EXT_TWEET UNIQUE ( ID_EXT_TWEET ) 
 );

CREATE TABLE PROJETO1.TB_QUOTED_TWEETS ( 
	ID_QUOTED            integer   ,
	TEXTO_QUOTED         varchar2(300)   ,
	ID_HASH              integer   ,
	ID_TWEET             integer  NOT NULL ,
	ID_RETWEET           integer  NOT NULL ,
	ID_USER_QUOTED       integer  NOT NULL ,
	CONSTRAINT PK_TB_QUOTED_TW_ID_QUOTED UNIQUE ( ID_QUOTED ) 
 );

ALTER TABLE PROJETO1.TB_EXTENDED_TWEETS ADD CONSTRAINT FK_TB_EXTENDED_TWEETS_TB_USER_MENTIONS FOREIGN KEY ( ID_USER_MENTIONS ) REFERENCES PROJETO1.TB_USER_MENTIONS( ID_USER_MENTIONS );

ALTER TABLE PROJETO1.TB_LOCALIDADE ADD CONSTRAINT FK_TB_LOCALIDADE_TB_COORDENADAS FOREIGN KEY ( ID_COORD ) REFERENCES PROJETO1.TB_COORDENADAS( ID_COORD );

ALTER TABLE PROJETO1.TB_QUOTED_TWEETS ADD CONSTRAINT FK_TB_QUOTED_TWEETS_TB_RETWEET FOREIGN KEY ( ID_RETWEET ) REFERENCES PROJETO1.TB_RETWEET( ID_RETWEET );

ALTER TABLE PROJETO1.TB_QUOTED_TWEETS ADD CONSTRAINT FK_TB_QUOTED_TWEETS_TB_USER_RETWEET FOREIGN KEY ( ID_RETWEET ) REFERENCES PROJETO1.TB_USER_RETWEET( ID_USER_RETWEET );

ALTER TABLE PROJETO1.TB_QUOTED_TWEETS ADD CONSTRAINT FK_TB_QUOTED_TWEETS_TB_TWEET FOREIGN KEY ( ID_TWEET ) REFERENCES PROJETO1.TB_TWEET( ID_TWEET );

ALTER TABLE PROJETO1.TB_QUOTED_TWEETS ADD CONSTRAINT FK_TB_QUOTED_TWEETS_TB_HASHTAGS FOREIGN KEY ( ID_HASH ) REFERENCES PROJETO1.TB_HASHTAGS( ID_HASH );

ALTER TABLE PROJETO1.TB_QUOTED_TWEETS ADD CONSTRAINT FK_TB_QUOTED_TWEETS_TB_USER_QUOTED FOREIGN KEY ( ID_USER_QUOTED ) REFERENCES PROJETO1.TB_USER_QUOTED( ID_USER_QUOTED );

ALTER TABLE PROJETO1.TB_TWEET ADD CONSTRAINT FK_TB_TWEET_TB_USER_TWEET FOREIGN KEY ( ID_USER_TWEET ) REFERENCES PROJETO1.TB_USER_TWEET( ID_USER_TWEET );

ALTER TABLE PROJETO1.TB_TWEET ADD CONSTRAINT FK_TB_TWEET_TB_LOCALIDADE FOREIGN KEY ( ID_LOCALIDADE ) REFERENCES PROJETO1.TB_LOCALIDADE( ID_LOCALIDADE );

ALTER TABLE PROJETO1.TB_TWEET ADD CONSTRAINT FK_TB_TWEET_TB_HASHTAGS FOREIGN KEY ( ID_HASH ) REFERENCES PROJETO1.TB_HASHTAGS( ID_HASH );

ALTER TABLE PROJETO1.TB_USER_MENTIONS ADD CONSTRAINT FK_TB_USER_MENTIONS_TB_RETWEET FOREIGN KEY ( ID_RETWEET ) REFERENCES PROJETO1.TB_RETWEET( ID_RETWEET );

ALTER TABLE PROJETO1.TB_USER_MENTIONS ADD CONSTRAINT FK_TB_USER_MENTIONS_TB_TWEET FOREIGN KEY ( ID_TWEET ) REFERENCES PROJETO1.TB_TWEET( ID_TWEET );
